---
name: "CI"

on:
  push:

jobs:
  tests:
    name: "${{ matrix.tox-envs }} with ${{ matrix.python-version }}"
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            os: "ubuntu-latest"
            tox-envs: "py37-server620"
          - python-version: "3.7"
            os: "ubuntu-latest"
            tox-envs: "py37"
          - python-version: "3.11"
            os: "ubuntu-latest"
            tox-envs: "py311"
          - python-version: "pypy-3.7"
            os: "ubuntu-latest"
            tox-envs: "pypy3"

    env:
      PY_COLORS: 1

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel tox
      - name: "Run tox targets for ${{ matrix.tox-envs }} with ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          python -m tox -v -e ${{ matrix.tox-envs }} -- -v --color=yes

  pre-tests:
    name: "PIP_PRE=1 ${{ matrix.tox-envs }} with ${{ matrix.python-version }}"
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            os: "ubuntu-latest"
            tox-envs: "py37-server620"
          - python-version: "3.7"
            os: "ubuntu-latest"
            tox-envs: "py37"
          - python-version: "3.11"
            os: "ubuntu-latest"
            tox-envs: "py311"
          - python-version: "pypy-3.7"
            os: "ubuntu-latest"
            tox-envs: "pypy3"

    env:
      PY_COLORS: 1

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel tox
      - name: "Run tox targets for ${{ matrix.tox-envs }} with ${{ matrix.python-version }} on ${{ matrix.os }}"
        continue-on-error: true
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          PIP_PRE=1 python -m tox -v -e ${{ matrix.tox-envs }} -- -v --color=yes

  flake8:
    env:
      PY_COLORS: 1

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"
      - name: "Install dependencies"
        shell: "bash"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip flake8 setuptools wheel
      - name: "Run flake8"
        shell: "bash"
        run: |
          set -xe -o nounset
          flake8 --config .flake8 src/devpi_constrained
